apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker 
  name: kernel-5.14.0-570.16.1
spec:
  osImageURL: quay.io/midu/kernel-5.14.0-570.16.1.el9_6.x86_64:4.16.37