FROM quay.io/midu/side-kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64:latest as kernel-query
#We can't use the `uname -r` as it will pick up the host kernel version
RUN rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' > /kernel-version.txt

# oc adm release info $(oc get clusterversion/version -ojsonpath={.status.desired.version}) --image-for=driver-toolkit
FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b53883ca2bac5925857148c4a1abc300ced96c222498e3bc134fe7ce3a1dd404 as builder
COPY --from=kernel-query /kernel-version.txt /kernel-version.txt

# Obtain the custom kernel packages to be able to target it during the kmod build.
RUN curl -O -L https://people.redhat.com/midu/kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64/kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64.rpm && \
    curl -O -L https://people.redhat.com/midu/kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64/kernel-core-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64.rpm && \
    curl -O -L https://people.redhat.com/midu/kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64/kernel-modules-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64.rpm && \
    curl -O -L https://people.redhat.com/midu/kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64/kernel-modules-extra-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64.rpm && \
    curl -O -L https://people.redhat.com/midu/kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64/kernel-devel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64.rpm

#Install custom kernel
RUN dnf install -y \
    kernel-$(cat /kernel-version.txt).rpm kernel-core-$(cat /kernel-version.txt).rpm \
    kernel-modules-$(cat /kernel-version.txt).rpm kernel-modules-extra-$(cat /kernel-version.txt).rpm \
    kernel-devel-$(cat /kernel-version.txt).rpm 

#Install build dependencies, these differ module by module
#This example uses: https://github.com/openshift-psap/simple-kmod
RUN dnf install -y make gcc

#Downloading kmod source and build it:
WORKDIR /
RUN git clone https://github.com/openshift-psap/simple-kmod.git
WORKDIR /simple-kmod
RUN make all KVER=$(cat /kernel-version.txt)

#Install kernel module on top of the image with the custom kernel:
FROM quay.io/midu/side-kernel-4.18.0-372.40.1.el8_6.iavf.bz2149746.bz2152493.x86_64:latest
COPY --from=builder /simple-kmod /simple-kmod
WORKDIR /simple-kmod
RUN make install KVER=$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}') && ostree container commit 

#clean-up, delete the module build dir.
RUN rm -rf /simple-kmod && ostree container commit