# Using a 4.16.37 image
# export OCP_VERSION="4.16.37"
# curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_VERSION/release.txt | grep -m1 'rhel-coreos' | awk -F ' ' '{print $2}'
ARG rhel_coreos_release
FROM ${rhel_coreos_release}
# RUN rpm-ostree cliwrap install-to-root / ## Removed due to https://issues.redhat.com/browse/OCPBUGS-37243

# Download kernel RPMs
RUN curl -k -O https://people.redhat.com/midu/kernel-6.12.4-0.test.el9_7.x86_64.rpm/kernel-6.12.4-0.test.el9_7.x86_64.rpm && \
	curl -k -O https://people.redhat.com/midu/kernel-6.12.4-0.test.el9_7.x86_64.rpm/kernel-core-6.12.4-0.test.el9_7.x86_64.rpm && \
	curl -k -O https://people.redhat.com/midu/kernel-6.12.4-0.test.el9_7.x86_64.rpm/kernel-modules-6.12.4-0.test.el9_7.x86_64.rpm && \
    curl -k -O https://people.redhat.com/midu/kernel-6.12.4-0.test.el9_7.x86_64.rpm/kernel-modules-core-6.12.4-0.test.el9_7.x86_64.rpm && \
    curl -k -O https://people.redhat.com/midu/kernel-6.12.4-0.test.el9_7.x86_64.rpm/kernel-modules-extra-6.12.4-0.test.el9_7.x86_64.rpm

# Install hotfix rpm
RUN rpm-ostree override replace \
        kernel-{,core-,modules-,modules-core-,modules-extra-}6.12.4-0.test.el9_7.x86_64.rpm && \
    ostree container commit

