# Using a 4.16.37 image
# export OCP_VERSION="4.16.37"
# curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_VERSION/release.txt | grep -m1 'rhel-coreos' | awk -F ' ' '{print $2}'
ARG rhel_coreos_release
FROM ${rhel_coreos_release}

RUN rpm-ostree cliwrap install-to-root /

# Download kernel RPMs
RUN curl -k -O https://download.eng.brq.redhat.com/brewroot/packages/kernel/5.14.0/427.61.1.el9_4/x86_64/kernel-5.14.0-427.61.1.el9_4.x86_64.rpm && \
    curl -k -O https://download.eng.brq.redhat.com/brewroot/packages/kernel/5.14.0/427.61.1.el9_4/x86_64/kernel-core-5.14.0-427.61.1.el9_4.x86_64.rpm && \
    curl -k -O https://download.eng.brq.redhat.com/brewroot/packages/kernel/5.14.0/427.61.1.el9_4/x86_64/kernel-modules-5.14.0-427.61.1.el9_4.x86_64.rpm && \
    curl -k -O https://download.eng.brq.redhat.com/brewroot/packages/kernel/5.14.0/427.61.1.el9_4/x86_64/kernel-devel-5.14.0-427.61.1.el9_4.x86_64.rpm && \
    curl -k -O https://download.eng.brq.redhat.com/brewroot/packages/kernel/5.14.0/427.61.1.el9_4/x86_64/kernel-modules-core-5.14.0-427.61.1.el9_4.x86_64.rpm && \
    curl -k -O https://download.eng.brq.redhat.com/brewroot/packages/kernel/5.14.0/427.61.1.el9_4/x86_64/kernel-modules-extra-5.14.0-427.61.1.el9_4.x86_64.rpm 

# Install
RUN rpm-ostree override replace \
        kernel-{,core-,modules-,modules-core-,modules-extra-}5.14.0-427.61.1.el9_4.x86_64.rpm && \
    ostree container commit
