# Using a 4.12.2 image
# export OCP_VERSION="4.12.2"
# curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_VERSION/release.txt | grep -m1 'rhel-coreos-8' | awk -F ' ' '{print $2}'
ARG rhel_coreos_release
FROM ${rhel_coreos_release}

# COPY runc-1.1.6-2.rhaos4.12.el8.x86_64.rpm to the layer
COPY selinux-policy-3.14.3-95.el8_6.8.noarch.rpm /selinux-policy-3.14.3-95.el8_6.8.noarch.rpm
COPY selinux-policy-targeted-3.14.3-95.el8_6.8.noarch.rpm /selinux-policy-targeted-3.14.3-95.el8_6.8.noarch.rpm
COPY systemd-239-58.el8_6.12.x86_64.rpm /systemd-239-58.el8_6.12.x86_64.rpm
COPY systemd-devel-239-58.el8_6.12.x86_64.rpm /systemd-devel-239-58.el8_6.12.x86_64.rpm
COPY systemd-journal-remote-239-58.el8_6.12.x86_64.rpm /systemd-journal-remote-239-58.el8_6.12.x86_64.rpm
COPY systemd-libs-239-58.el8_6.12.x86_64.rpm /systemd-libs-239-58.el8_6.12.x86_64.rpm
COPY systemd-pam-239-58.el8_6.12.x86_64.rpm /systemd-pam-239-58.el8_6.12.x86_64.rpm
COPY systemd-udev-239-58.el8_6.12.x86_64.rpm /systemd-udev-239-58.el8_6.12.x86_64.rpm
RUN mkdir -p /etc/selinux/policy/
RUN rpm-ostree override replace /systemd-239-58.el8_6.12.x86_64.rpm /systemd-devel-239-58.el8_6.12.x86_64.rpm /systemd-journal-remote-239-58.el8_6.12.x86_64.rpm /systemd-libs-239-58.el8_6.12.x86_64.rpm /systemd-pam-239-58.el8_6.12.x86_64.rpm /systemd-udev-239-58.el8_6.12.x86_64.rpm /selinux-policy-3.14.3-95.el8_6.8.noarch.rpm /selinux-policy-targeted-3.14.3-95.el8_6.8.noarch.rpm && \
    rpm-ostree cleanup -m && mv /var/lib/selinux/targeted/ /etc/selinux/policy/targeted/ && rm -rf /var/* && systemctl enable systemd-pstore.service\
    ostree container commit