apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: kernel-5.14.0-402
spec:
  osImageURL: quay.io/jclaret/kernel-5.14.0-402.el9.x86_64:4.14.5
