apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker 
  name: kernel-6.15.0-0.rc7.58
spec:
  osImageURL: quay.io/midu/kernel-6.15.0-0.rc7.58.fc43.x86_64:4.16.37