# Using a 4.16.37 image
# export OCP_VERSION="4.16.37"
# curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_VERSION/release.txt | grep -m1 'rhel-coreos' | awk -F ' ' '{print $2}'
ARG rhel_coreos_release
FROM ${rhel_coreos_release}

RUN rpm-ostree cliwrap install-to-root /

# Download kernel RPMs
RUN curl -k -O https://kojipkgs.fedoraproject.org/packages/kernel/6.15.0/0.rc7.58.fc43/x86_64/kernel-6.15.0-0.rc7.58.fc43.x86_64.rpm && \
    curl -k -O https://kojipkgs.fedoraproject.org/packages/kernel/6.15.0/0.rc7.58.fc43/x86_64/kernel-core-6.15.0-0.rc7.58.fc43.x86_64.rpm && \
    curl -k -O https://kojipkgs.fedoraproject.org/packages/kernel/6.15.0/0.rc7.58.fc43/x86_64/kernel-modules-6.15.0-0.rc7.58.fc43.x86_64.rpm && \
    curl -k -O https://kojipkgs.fedoraproject.org/packages/kernel/6.15.0/0.rc7.58.fc43/x86_64/kernel-devel-6.15.0-0.rc7.58.fc43.x86_64.rpm && \
    curl -k -O https://kojipkgs.fedoraproject.org/packages/kernel/6.15.0/0.rc7.58.fc43/x86_64/kernel-modules-core-6.15.0-0.rc7.58.fc43.x86_64.rpm && \
    curl -k -O https://kojipkgs.fedoraproject.org/packages/kernel/6.15.0/0.rc7.58.fc43/x86_64/kernel-modules-extra-6.15.0-0.rc7.58.fc43.x86_64.rpm 

# Install the kernel RPMs and apply the https://issues.redhat.com/browse/OCPBUGS-30149 WA than commit the changes
# to the ostree repo.
RUN rpm-ostree override replace \
        kernel-{,core-,modules-,modules-core-,modules-extra-}6.15.0-0.rc7.58.fc43.x86_64.rpm && \
    mv /usr/libexec/rpm-ostree/wrapped/rpm /usr/bin/rpm && \
    ostree container commit
